version: '2'
services:
  laradock:
    image: laradock
    build: 
      context: /home/dalibor/projects/laradock
      dockerfile: /home/dalibor/projects/laradock/docker/Dockerfile
    container_name: laradock
    ports:
      - 8080:80
      - 5656:8080
    volumes:
      - ../../app:/var/www/app
    privileged: true


