version: '2'
services:
  laradock:
    image: laradock
    hostname: laradocksrv
    extra_hosts:
      - "laradock:127.0.0.1"
    build: 
      context: /Users/DMenkovic/projects/docker-hub/laradock
      dockerfile: /Users/DMenkovic/projects/docker-hub/laradock/docker/Dockerfile
    container_name: laradock
    ports:
      - 10080:80
    volumes:
      - ../../app:/var/www/app
    privileged: true


